name: Build Arch Package

on:
  push:
    tags:
      - 'v*'
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Build inside Arch docker
        run: |
          docker run --rm -v "$PWD:/src" archlinux/archlinux:base-devel bash -c "
            pacman -Syu --noconfirm cairo dconf gcc-libs glib2 glibc gsettings-desktop-schemas gtk3 hicolor-icon-theme libhandy libx11 pango util-linux-libs vte3 docbook-xsl git glib2-devel meson yelp-tools libnautilus-extension --needed &&
            cp /src/.github/makepkg.conf /etc/makepkg.conf.d/ &&
            useradd -m builder && chown -R builder:builder /src &&
            su - builder -c 'cd /src && makepkg -C'
          "

      - name: Upload pkg to release
        uses: softprops/action-gh-release@v3
        with:
          files: ./*.pkg.tar.zst
          overwrite_files: true
          body: "Automated build for tag ${{ github.ref_name }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
